language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
  yarn: true
script:
  yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: ./
  on:
    branch: master
